os: linux
language: node_js
node_js:
 - stable
 - lts/*
cache:
    directories:
      - node_modules
jobs:
  include:
    - stage: release
      scripts:
        - npm install codecov -g
      after_success:
        - codecov
